/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DataTypeType = "keywords";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DataSetDataTypes {
  data_set_id: string;
  data_type_id: string;
}

export interface DataSets {
  id: Generated<string>;
  name: string;
}

export interface DataTypes {
  content: string[];
  description: string | null;
  id: Generated<string>;
  name: string;
  threshold: Generated<number>;
  type: DataTypeType;
}

export interface DB {
  data_set_data_types: DataSetDataTypes;
  data_sets: DataSets;
  data_types: DataTypes;
}
